# Generated by Django 5.2.8 on 2025-11-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='edad',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='genero',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gmail',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
