# Generated by Django 5.2.8 on 2025-11-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_edad_member_genero_member_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='genero',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
